// <auto-generated />
namespace AdveChan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BanAdmin290715 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BanAdmin290715));
        
        string IMigrationMetadata.Id
        {
            get { return "201507282249437_BanAdmin290715"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
